//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp11
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int id { get; set; }
        public string names { get; set; }
        public string email { get; set; }
        public string grad { get; set; }
        public Nullable<int> s_password { get; set; }
        public Nullable<int> td_id { get; set; }
    
        public virtual teacher teacher { get; set; }
    }
}
